[tool.poetry]
name = "casio-checker"
version = "0.1.0"
description = ""
authors = ["Vasil Ivanov <ivanovvasil99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.0.1"
beautifulsoup4 = "^4.12.3"
pymongo = {extras = ["srv"], version = "^4.10.1"}
requests = "^2.32.3"
pydantic = "^2.10.4"
brevo-python = "^1.1.2"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
