# cron job that runs every two days and runs the ./mvr/check-obligations.sh bash script
# from the main branch
# with the EGN and CAR_NO environment variables set from github secrets
name: Check MVR obligations
on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

env:
  EGN: ${{ secrets.EGN }}
  CAR_NO: ${{ secrets.CAR_NO }}

jobs: 
  check_mvr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Set permissons
        run: chmod +x ./mvr/check-obligations.sh
      
      - name: Run check-obligations.sh
        id: check-obligations
        run: |
          OBLIGATIONS_CHECK_RESULT=$(./mvr/check-obligations.sh)
          {
            echo 'CHECK_RESULT<<EOF'
            echo "$OBLIGATIONS_CHECK_RESULT"
            echo EOF
          } >> $GITHUB_ENV

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: ${{ secrets.BREVO_SMTP }}
          smtp-port:  ${{ secrets.BREVO_PORT }}
          smtp-secure: false
          from-email: ${{ secrets.OWN_EMAIL }}
          to-email: ${{ secrets.OWN_EMAIL }}
          username: ${{ secrets.BREVO_LOGIN }}
          password: ${{ secrets.BREVO_PASS }}
          subject: Проверка за глоби от КАТ
          body: "${{ env.CHECK_RESULT }}"
